### ISSUE TITLE
Multiple combinations of scores appear on !scores

### ISSUE THREAD

**Issue by chriskol** [yincrash/hubot-trivia-game#14]
Using on slack.

I get 11 messages from hubot each time I use !scores. It looks like in the first message, it lists the first member of my Slack, then in the second, it lists the first and second member, then in the third it lists the first second and third member, and so on until there are 11 messages with the final message showing everyone and the score.  What's up with that?

**Comment by cartfisk** [comment]
There was an accidental tab putting the respond statement inside the loop that compiles user scores instead of afterward.

**Comment by yincrash** [comment]
Merged @cartfisk's fix.
