### ISSUE TITLE
Trivia Game encounters an error on answers.

### ISSUE THREAD

**Issue by perrygoy** [yincrash/hubot-trivia-game#17]
### Issue Description:
Trivia Game encounters an error when a user attempts to answer a question. This has been happening since yesterday (March 6th, 2018), around midday. Here is an example of the log message:
`[Wed Mar 07 2018 12:08:06 GMT-0600 (CST)] ERROR undefined`

### Expected Behavior:
Trivia Game responds to answers by awarding points if the answer is correct, or by telling the user that the answer is incorrect.

### Version:
v1.0.8

### Environment:
Slack

### Prereq(s):
Jeopardy Questions file is downloaded from the following URL, and placed in `res/questions.json` http://www.reddit.com/r/datasets/comments/1uyd0t/200000_jeopardy_questions_in_a_json_file

### Steps to Reproduce:
1. Launch hubot with `hubot-loaded-questions` installed and added to the `external_scripts.json` file.
1. Begin a trivia game by saying !trivia
1. Attempt to answer the question by saying !a answer
1. Observe there no response from hubot.
1. Observe there is the message `ERROR undefined` in the logs.

**Comment by yincrash** [comment]
Fixed by #18
