### ISSUE TITLE
Score is always $0 for the user

### ISSUE THREAD

**Issue by ravikiranj** [yincrash/hubot-trivia-game#8]
The score is always $0 even after the user answers a question correctly. Any idea what I'm doing wrong ?

```
HipChat Bot 10:55 AM 
Answer with !a or !answer
For $1600 in the category of BACK IN 1906:
'In 1906 there were 90 of these; nearly two-thirds of them were Republican'

Tom Alexander 10:55 AM
!a senators

HipChat Bot 10:55 AM
@TomA YOU ARE CORRECT!!1!!!111!! The answer is senators
@TomA Score: 1600

Ravikiran Janardhana 10:55 AM
!score Tom Alexander
HipChat Bot 10:55 AM
Tom Alexander - $0
```

**Comment by yincrash** [comment]
It uses his username, not his visible name. Try `!score @TomA`

**Comment by ravikiranj** [comment]
Same result.
```
Ravikiran Janardhana - 11:24 AM
!score @TomA

HipChat Bot 11:24 AM
There is no score for @toma
```

**Comment by ehammersley** [comment]
I noticed the same thing until I realized it wasn't handling the @.  Do !score TomA and it should work.

That being said !score all doesn't seem to work as written.

**Comment by D8T** [comment]
Any solution to the scores not being displayed?  I pulled from here, it indicated the NPM installed version was allready up to date.  Running on hipchat, no scores logged.

**Comment by yincrash** [comment]
I don't have a hipchat instance to test on at the moment. When answering a question correctly, does the bot return a score that is non-zero? for example, in hubot's log:
```
[Fri Aug 05 2016 02:39:43 GMT-0400 (EDT)] DEBUG yincrash answered correctly.
[Fri Aug 05 2016 02:39:43 GMT-0400 (EDT)] DEBUG Sending reply
[Fri Aug 05 2016 02:39:43 GMT-0400 (EDT)] DEBUG Sending to trivia: yincrash: Score: 538300
```

**Comment by D8T** [comment]
This seems a silly question, but I can't find the logs.  
I'm hosting Hubot on openshift and have set $ rhc env set HUBOT_LOG_LEVEL="debug"
Any help would be appreciated, the fellas love the trivia game.

**Comment by d8tee** [comment]
I didn't have the latest version pulled down from the website, double checked and did that. Now it's keeping score.
